# Generated by Django 4.0.2 on 2022-11-07 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
