# Generated by Django 4.0.2 on 2022-11-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_followers_remove_post_following_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
